#!/bin/bash
sign=true
message="some changes"
for i in $*
do
  index=$[index+1]
  if [ $i = "-ns" ]
  then
    sign=false
  fi

  if [ $i = "-h" ]
  then
    echo "Usage: commit [-ns] [-m <message>]"
  fi

  if [ $i = "-v" ]
  then
    echo "Version: 0.1"
  fi

  if [ $i = "-a" ]
  then
    echo "Author: ZhouHaoyu"
  fi

  if [ $i = "-m" ]
  then
    _index=`expr $index + 1`
    message=$(echo $* | cut -d " " -f $_index)
  fi
done

git add .
if [ $sign = true ]
then
  echo "your commit will be signed"
  git commit -s -m "$message"
else
  git commit -m "$message"
fi
git push